### ISSUE TITLE
Container crashed with let detailDefined = typeof body.detail !== 'undefined' error

### ISSUE THREAD

**Issue by Aboitier** [TheConnMan/docker-hub-rss#50]
I realized today that the container crashed after 2 months+ of good service.

```
/app/node_modules/docker-hub-api/src/api.js:1310
            let detailDefined = typeof body.detail !== 'undefined';
                                            ^

TypeError: Cannot read properties of undefined (reading 'detail')
    at Object.bodyHasError (/app/node_modules/docker-hub-api/src/api.js:1310:45)
    at Object.<anonymous> (/app/node_modules/docker-hub-api/src/api.js:1359:38)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Any idea what could have caused this ?

Thanks for the great tool!

**Comment by TheConnMan** [comment]
Based on the error, it seems like there was a temporary issue with the DockerHub API which wasn't handled well by Docker Hub RSS. If you restart the container, does it error out again?

I'm glad you're enjoying it!

**Comment by Aboitier** [comment]
It works perfectly on restart. Just wanted to notify error for dev purposes. Thanks for the quick answer!

**Comment by TheConnMan** [comment]
Understood. Thanks for letting me know!
