### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'detail')

### ISSUE THREAD

**Issue by Aboitier** [TheConnMan/docker-hub-rss#51]
Had this bug that exited the container. If it can help. Not sure about the initial request though.

```
TypeError: Cannot read properties of undefined (reading 'detail')
    at Object.bodyHasError (/app/node_modules/docker-hub-api/src/api.js:1310:45)
    at Object.<anonymous> (/app/node_modules/docker-hub-api/src/api.js:1359:38)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
error Command failed with exit code 1.
```

**Comment by TheConnMan** [comment]
Thanks @Aboitier. This looks similar to #50. I'm not sure what causes it, but if you see it again please provide what you think triggered it. A container restart should fix it.

**Comment by Aboitier** [comment]
You are right that's what I decided to do. Thanks for the quick answer.
